# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo 1
        run: |
          echo $SECRET01 > file01
          wc -l file01
      
        env:
          SECRET01: ${{ secrets.SECRET01 }}
      - name: multi line
        run: |
          ls -l
          pwd
          npm -v
          
